### ISSUE TITLE
I2P installation is broken due to outdated repository sources

### ISSUE THREAD

**Issue by errantelectron** [shermand100/PiNodeXMR#124]
The sources list file `etc/apt/sources.list.d/i2p.list` in the PiNodeXMR repository has not been updated, and seems to overwrite the apt sources for I2P with outdated content any time the user tries to set up I2P integration.

The i2p installation script appears to have been updated in an attempt to fix this, but still uses that out of date file.

Even if the user separately edits their local` /etc/apt/sources.list.d/i2p.list` or manually adds the up to date sources with `sudo apt-add-repository ppa:i2p-maintainers/i2p`, attempting to run PiNodeXMR's I2P installation then overwrites outdated content again before it begins - causing the installation to fail (though PiNodeXMR will wrongly report successful installation of I2P).

**Comment by errantelectron** [comment]
I'm not as knowledgeable about this as one might assume from my initial post (which was the result of a lot of tinkering trying to get I2P configured) but that looks good.

Won't have an opportunity to test it for another day or two, but happy to do that if you want a second person to try it before merging.

**Comment by shermand100** [comment]
Ok, so I've merged that change into the main. If you want to try it out then just do a PiNodeXMR update from the terminal settings menu (less than 5 mins), then you'll have that new I2P install script.

We can re-open this if it doesn't do as expected.

**Comment by errantelectron** [comment]
That looks almost identical to what I had tried, with the one difference that I previously did the forced PiNodeXMR update prior to uninstalling I2P rather than afterward.

Repeating in the same order as you I get the same error though.

![Image](https://github.com/user-attachments/assets/ef7119ba-9fd4-4d78-9a7a-112a7e5ebd42)

I suspect that the problem might not lie in the PiNodeXMR code base though, and that perhaps my earlier attempts to get I2P installed may have somehow broken something elsewhere relating to the I2P configuration path.

I'll try a complete fresh reflash of my pi next and then re-attempt, though it's probably going to be a week from now before I get to test that.

**Comment by shermand100** [comment]
Just a thought...

Did you install I2P under the user 'pinodexmr' when prompted or leave it as the default 'i2pavc'

It may not find it if it left as 'i2pavc'

I setup as detailed here: ( Except I think the default RAM usage is now 256, whatever is default is fine except the username)

https://github.com/shermand100/PiNodeXMR/wiki/i2p-Setup-and-Use

**Comment by errantelectron** [comment]
Update: Even with a fresh reflash of Ubuntu, fresh install of PiNodeXMR, and making sure to specify the correct username on first running the I2P installer, I still get the very same error.

I can only assume there is some kind of incompatibility in how the I2P packages get configured on the device I'm using (Rock Pi 4).

The default username for radxa's Ubuntu images for this device is "rock" rather than "pi" or "ubuntu", but I believe the only installation problem this should cause is a failure of PiNodeXMR to automatically deactivate the default user account?

**Comment by errantelectron** [comment]
I've tried creating a "pi" user, adding that user to the sudoers group, and re-running the first stage of the ubuntu install script as that user, then logging back in as pinodexmr and doing a forced update through the settings menu (admittedly I did not do a total reflash this time around, as I don't feel like repasting the Rock Pi heatsink a second time, which has to be pulled to get at the eMMC).

Then as root I've run 
`apt remove i2p -y && apt autoremove -y
rm -r /var/lib/i2p
rm -r /usr/share/i2p
rm /etc/default/i2p`

On returning to the pinodexmr user running the I2P installation via the setup menu still gives the same error. I notice also that the I2P installer is defaulting to "pinodexmr" despite the attempt to remove previous I2P configurations, so I'm suspecting there's still some other remaining location I haven't found where I2P configuration details are getting stored.

At this point I'm ready to give up on trying to get I2P working on this device though, and will either stick with clearnet usage or change hardware.

**Comment by shermand100** [comment]
Hi again, sorry for the delay, travelling with work.

So this is just a quick glance at looking for the solution, I'll have more time to dig into this more on Monday.

The Rock4 Ubuntu official images seem to be a bit dated (2021)
https://github.com/radxa/rock-pi-images-released/releases

However this shouldn't be an obvious issue as the I2P docs are saying Ubuntu Bionic 18.04 or newer should work, so despite being old images are 3 years within the cycle of compatibility.

I also run my personal Node on the Rock Pi 4A, which is showing my system at some point has self updated

<img width="493" height="171" alt="Image" src="https://github.com/user-attachments/assets/2e7489ea-175a-406a-b403-5a0a33e18a14" />

`lsb_release -a`

How current is yours?
I'm struggling to think of what else could be different?
